export const Constance = {
  NOTIFY_USER: 'NOTIFY_USER',
  DISABLE_BALANCE_ON_ADD: 'DISABLE_BALANCE_ON_ADD',
  DISABLE_BALANCE_ON_EDIT: 'DISABLE_BALANCE_ON_EDIT',
  ALLOW_REGISTRATION: 'ALLOW_REGISTRATION'
};